stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

build:
  stage: build
  image: docker:latest
  before_script:
    - apk update && apk add --no-cache docker-compose
  script:
    - docker-compose build

test:
  stage: test
  image: node:14
  before_script:
    - cd frontend
    - npm install
  script:
    - npm test

deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - apk update && apk add --no-cache docker-compose
  script:
    - docker-compose up -d
  only:
    - master
