stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache py3-pip
    - pip install docker-compose
  script:
    - docker-compose build

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache py3-pip
    - pip install docker-compose
  script:
    - docker-compose up -d
