stages:
  - build
  - test_frontend
  - test_backend
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  JWT_SECRET: $JWT_SECRET

services:
  - docker:dind

build:
  stage: build
  image: docker:latest
  before_script:
    - apk update && apk add --no-cache docker-compose
  script:
    - docker-compose build

test_frontend:
  stage: test_frontend
  image: node:22
  before_script:
    - cd frontend
    - npm install
    - npm install -g npm@latest  # Оновлення npm
  script:
    - npm test

test_backend:
  stage: test_backend
  image: node:22
  services:
    - name: mysql:8
      alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_DATABASE: myapp
  before_script:
    - cd backend
    - npm install
    - npm install -g npm@latest  # Оновлення npm
  script:
    - npm test

deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - apk update && apk add --no-cache docker-compose
  script:
    - docker-compose up -d
  only:
    - master
