version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_USER: root
      DATABASE_PASSWORD: rootpassword
      DATABASE_NAME: myapp

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
